spring.application.name=com.seguros.vehiculares
server.port=8080

#PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5433/mibanco
spring.datasource.username=itocto
spring.datasource.password=Sistema2026
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

#Redis
spring.cache.type=redis
spring.data.redis.host=redis
spring.data.redis.port=6379

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
logging.level.org.springframework=INFO
spring.main.web-application-type=reactive